/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: 'var(--color-border)',
        primary: {
          99: 'var(--color-primary-99)',
          95: 'var(--color-primary-95)',
          90: 'var(--color-primary-90)',
          80: 'var(--color-primary-80)',
          70: 'var(--color-primary-70)',
          60: 'var(--color-primary-60)',
          50: 'var(--color-primary-50)',
          40: 'var(--color-primary-40)',
          30: 'var(--color-primary-30)',
          20: 'var(--color-primary-20)',
          10: 'var(--color-primary-10)',
        },
        neutral: {
          99: 'var(--color-neutral-99)',
          95: 'var(--color-neutral-95)',
          90: 'var(--color-neutral-90)',
          80: 'var(--color-neutral-80)',
          70: 'var(--color-neutral-70)',
          60: 'var(--color-neutral-60)',
          50: 'var(--color-neutral-50)',
          40: 'var(--color-neutral-40)',
          30: 'var(--color-neutral-30)',
          20: 'var(--color-neutral-20)',
          950: 'var(--color-neutral-950)',
        },
        success: {
          99: 'var(--color-success-99)',
          95: 'var(--color-success-95)',
          90: 'var(--color-success-90)',
          80: 'var(--color-success-80)',
          70: 'var(--color-success-70)',
          60: 'var(--color-success-60)',
          50: 'var(--color-success-50)',
          40: 'var(--color-success-40)',
          30: 'var(--color-success-30)',
          20: 'var(--color-success-20)',
          950: 'var(--color-success-950)',
        },
        error: {
          99: 'var(--color-error-99)',
          95: 'var(--color-error-95)',
          90: 'var(--color-error-90)',
          80: 'var(--color-error-80)',
          70: 'var(--color-error-70)',
          60: 'var(--color-error-60)',
          50: 'var(--color-error-50)',
          40: 'var(--color-error-40)',
          30: 'var(--color-error-30)',
          20: 'var(--color-error-20)',
          950: 'var(--color-error-950)',
        },
        warning: {
          99: 'var(--color-warning-99)',
          95: 'var(--color-warning-95)',
          90: 'var(--color-warning-90)',
          80: 'var(--color-warning-80)',
          70: 'var(--color-warning-70)',
          60: 'var(--color-warning-60)',
          50: 'var(--color-warning-50)',
          40: 'var(--color-warning-40)',
          20: 'var(--color-warning-20)',
          950: 'var(--color-warning-950)',
        },
      }
    },
  },
  plugins: [],
}